import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import { Icon } from '@/icons';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const links = [
    {
        text: 'Get Started',
        href: 'https://docs.midjourney.com/',
    },
    {
        text: 'Showcase',
        href: 'https://www.midjourney.com/showcase/recent/',
    },
    {
        text: 'Join the Beta',
        href: 'https://discord.com/invite/midjourney',
    },
    {
        text: 'Sign In',
        href: 'https://discord.com/oauth2/authorize?client_id=936929561302675456&scope=identify%20email%20guilds.members.read%20guilds.join%20role_connections.write&response_type=code&redirect_uri=https%3A%2F%2Fwww.midjourney.com%2Fapi%2Fauth%2Fcallback%2Fdiscord&state=XEjJGSJdBrJmUwr8WBY-PJ47bznxDjwmqoqL6PQNkAA',
    },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex h-full w-full justify-center px-4 sm:px-8">
                    <div className="flex h-full w-full max-w-7xl flex-col space-y-3">
                        <header className="flex h-16 w-full items-center justify-between">
                            <Icon type="logo" className="h-12 w-12" />
                            <div className="flex space-x-8">
                                {links.map(({ text, href }) => (
                                    <Link href={href} key={text}>
                                        <p>{text}</p>
                                    </Link>
                                ))}
                            </div>
                        </header>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
